Задание собрать данные о агентов и узнать кто больше всех дает прибыли бизнесу. И тех кого отрицательный прибыль надо переподготовить!

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Импортируем библиотеки

In [98]:
import pandas as pd

Читаем данные с Таблицы-excel

In [118]:
df = pd.read_excel('tabl1.xlsx')

Поменяем слегка Датафрейм, уберем лишние столбцы и добавим чистую прибыль между продажей и закупками.

In [119]:
df.drop(["Код товара", "Ед.изм."], axis=1, inplace=True)
df["Прибыль"] = df["Сумма в ценах продажи"] - df["Сумма в ценах закупки"]

Теперь смотрим на список агентов.

In [120]:
list_agents = df["Агент"].drop_duplicates()
list_agents

0       Агент20
7        Агент7
375     Агент13
414     Агент22
494     Агент15
503      Агент8
1370    Агент21
2127     Агент9
2180    Агент16
2205    Агент14
2233    Агент19
2313    Агент17
2342     Агент5
2344     Агент6
2380     Агент1
2412     Агент4
2548     Агент3
2625    Агент12
2658    Агент11
2740    Агент24
3389    Агент18
3676    Агент23
3798     Агент2
Name: Агент, dtype: object

Смотрим на общий отчет

In [121]:
df["Прибыль"].describe(include='all')

count    4520.000000
mean      121.770170
std       182.590068
min       -63.597800
25%        54.300000
50%        78.447600
75%       131.119200
max      4202.000000
Name: Прибыль, dtype: float64

Групируем таблицу с агентами и описательной аналитики

In [128]:
descriptive_stats = df.groupby('Агент')['Прибыль'].agg(['count', 'mean', 'std', 'min', 'max', 'median', 'sum'])

In [130]:
descriptive_stats.sort_values(by='sum', ascending=False)

,count,mean,std,min,max,median,sum
Агент,,,,,,,
Агент20,1796,126.305526,156.025165,-48.7578,3481.4387,89.21840,226844.72490
Агент22,1900,103.624308,80.348537,-63.5978,889.1736,78.28300,196886.18470
Агент9,138,388.926324,585.891737,37.4594,4202.0000,201.03550,53671.83270
Агент13,221,88.876176,124.035497,3.7020,1460.1600,61.02810,19641.63490
Агент3,13,1207.163508,1049.528138,261.6732,3870.3000,949.17000,15693.12560
Агент19,116,67.692446,121.102183,5.6516,1246.4376,41.19420,7852.32374
Агент7,42,136.783495,190.738534,1.9394,758.7896,63.57265,5744.90680
Агент15,49,87.246742,69.861135,24.5592,394.5956,67.32400,4275.09034
Агент11,35,80.041569,38.891489,24.5386,192.2530,76.96410,2801.45490
Агент5,39,70.677677,43.054268,19.6148,196.2495,69.27120,2756.42940
Агент8,34,70.971326,41.037418,19.6148,196.2495,67.49880,2413.02510
Агент14,22,109.168177,108.278260,21.9702,517.5000,86.14430,2401.69990
Агент24,24,93.235687,53.177294,11.6505,204.1078,97.79825,2237.65650
Агент16,22,68.149527,42.829907,18.2102,187.9336,62.23940,1499.28960
Агент4,18,80.537994,71.530232,14.7042,256.2600,57.77050,1449.68390
Агент6,13,104.766423,77.085589,44.1300,258.7500,66.10440,1361.96350
Агент23,10,86.268040,38.959841,42.7000,175.9430,80.10670,862.68040
Агент1,9,79.973644,48.086333,35.1705,180.6930,52.82550,719.76280
Агент2,8,66.536600,28.096968,9.0385,88.3432,76.09885,532.29280
Агент18,4,91.913100,32.415379,68.0768,136.7532,81.41120,367.65240
Агент12,3,68.846133,9.374254,61.6480,79.4464,65.44400,206.53840
Агент17,3,43.009600,15.783661,25.5000,56.1444,47.38440,129.02880
Агент21,1,52.188500,NaN,52.1885,52.1885,52.18850,52.18850

Вывод.

Лучшие агенты - это агент20, агент22, агент9, так как занимают топ-3 агентов по прибыли.

На переподготовку лучше отправить агента21, так как у него самая маленькая прибыль.